### ISSUE TITLE
BinstarError when uploading package

### ISSUE THREAD

**Issue by bekozi** [Anaconda-Server/anaconda-client#116]
I am encountering an error when attempting to upload a successfully built conda package to binstar (Ubuntu 14.04.1).

```sh
$ binstar --version
binstar Command line client (version 0.8)

$ binstar --verbose upload -c dev /home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2
detecting package type ...
[debug] Testing if conda package ..
[debug] This is a conda package
conda
extracting package attributes for upload ...
[BinstarError] Trouble reading metadata from '/home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2'. Is this a valid conda package
```

I pulled out the info folder from the built package and posted it here: https://www.dropbox.com/s/yxkezl35xcfk33s/info-gcc-4.8.2.tar.gz?dl=0.

Please let me know if you need anything else.

@rokuingh

**Comment by srossross** [comment]
@bekozi can you update to the latest binstar client? This should be 0.10.1

```
pip install binstar
```

**Comment by bekozi** [comment]
Updated and unfortunately still getting the same error:

```sh
$ binstar --version
binstar Command line client (version 0.10.1)

$ binstar --verbose upload -c dev /home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2
detecting package type ...
[debug] Testing if conda package .. 
[debug] This is a conda package 
conda
extracting package attributes for upload ...
[BinstarError] Trouble reading metadata from '/home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2'. Is this a valid conda package 
```

**Comment by srossross** [comment]
OK, sorry. Can you run binstar upload with the `--show-traceback` option.
```
binstar --verbose --show-traceback upload -c dev /home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2
```

**Comment by bekozi** [comment]
It's a MemoryError. I am running the build/upload on a small instance with only 1 GB of memory. The compressed package is relatively large (145 MB).

```sh
$ binstar --verbose --show-traceback upload -c dev /home/ubuntu/anaconda/conda-bld/linux-64/gcc-4.8.2-0.tar.bz2
detecting package type ...
[debug] Testing if conda package .. 
[debug] This is a conda package 
conda
extracting package attributes for upload ...
[MemoryError] 
Traceback (most recent call last):
  File "/home/ubuntu/anaconda/bin/binstar", line 9, in <module>
    load_entry_point('binstar==0.10.1', 'console_scripts', 'binstar')()
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 94, in main
    description=__doc__, version=version)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/binstar_client/scripts/cli.py", line 76, in binstar_main
    return args.main(args)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/binstar_client/commands/upload.py", line 168, in main
    package_attrs, release_attrs, file_attrs = get_attrs(package_type, filename)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/binstar_client/utils/detect.py", line 81, in get_attrs
    return detectors[package_type](filename, fileobj)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/binstar_client/inspect_package/conda.py", line 53, in inspect_conda_package
    index = json.loads(index.read().decode())
  File "/home/ubuntu/anaconda/lib/python2.7/tarfile.py", line 822, in read
    buf += self.fileobj.read()
  File "/home/ubuntu/anaconda/lib/python2.7/tarfile.py", line 742, in read
    return self.readnormal(size)
  File "/home/ubuntu/anaconda/lib/python2.7/tarfile.py", line 749, in readnormal
    self.fileobj.seek(self.offset + self.position)
  File "/home/ubuntu/anaconda/lib/python2.7/tarfile.py", line 691, in seek
    self.read(pos - self.pos)
  File "/home/ubuntu/anaconda/lib/python2.7/tarfile.py", line 681, in read
    self.buf = "".join(b)
MemoryError
 
```

**Comment by bekozi** [comment]
I was able to successfully upload the package using a machine with more memory. Thanks for the help. I'm not sure if you want to close the issue, so will leave it open for now...

**Comment by srossross** [comment]
Thanks @bekozi. I will keep this open. I need to better distinguish errors that are not caused by a badly constructed conda package.
