### ISSUE TITLE
develop branch tests fail on py3

### ISSUE THREAD

**Issue by rafaelhbarros** [Anaconda-Server/anaconda-client#220]
```
....F.../Users/rdebarros/work/anaconda-build/binstar_build_client/worker_commands/register.py:39: PendingDeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5 and will be removed in Python 3.7
  if platform.dist()[0]:
Using anaconda-server api site https://api.anaconda.org
test_user's .ss....Using anaconda-server api site https://api.anaconda.org
.Using anaconda-server api site https://api.anaconda.org
.Using anaconda-server api site https://api.anaconda.org
.Using anaconda-server api site https://api.anaconda.org
.Using anaconda-server api site https://api.anaconda.org
.F.E.................
======================================================================
ERROR: test_no_file (binstar_client.utils.notebook.tests.test_base.HasEnvironmentTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdebarros/work/anaconda-client/binstar_client/utils/notebook/__init__.py", line 46, in has_environment
    with open(nb_file) as fb:
FileNotFoundError: [Errno 2] No such file or directory: 'no-file'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rdebarros/work/anaconda-client/binstar_client/utils/notebook/tests/test_base.py", line 41, in test_no_file
    has_environment("no-file")
  File "/Users/rdebarros/work/anaconda-client/binstar_client/utils/notebook/__init__.py", line 52, in has_environment
    except (IOError, nbformat.reader.NotJSONError):
AttributeError: 'NoneType' object has no attribute 'reader'

======================================================================
FAIL: test_bdist_egg (binstar_client.inspect_package.tests.test_pypi.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdebarros/work/anaconda-client/binstar_client/inspect_package/tests/test_pypi.py", line 114, in test_bdist_egg
    self.assertEqual(expected_file_data[key], file_data[key])
AssertionError: None != 'py2.7'

======================================================================
FAIL: test_has_environment (binstar_client.utils.notebook.tests.test_base.HasEnvironmentTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rdebarros/work/anaconda-client/binstar_client/utils/notebook/tests/test_base.py", line 37, in test_has_environment
    assert has_environment(self.data_dir('notebook_with_env.ipynb'))
AssertionError

----------------------------------------------------------------------
Ran 40 tests in 1.212s

FAILED (failures=2, errors=1, skipped=2)

**Comment by rafaelhbarros** [comment]
The HasEnvironmentTest are fixed just by installing a dependency.

**Comment by rafaelhbarros** [comment]
No code changes required. Only setup.

**Comment by stephenakearns** [comment]
Thanks @rafaelhbarros  - when you say setup, what do you mean - The developer's local environment?

**Comment by rafaelhbarros** [comment]
Yes, my local env
