### ISSUE TITLE
`anaconda login` doesn't work on Mac OS X with miniconda3

### ISSUE THREAD

**Issue by talumbau** [Anaconda-Server/anaconda-client#234]
Error message:
```
0054-tjalumbaugh:conda.recipe talumbau$ anaconda login
Using anaconda-server api site https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/Users/talumbau/miniconda3/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/Users/talumbau/miniconda3/lib/python3.3/site-packages/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/Users/talumbau/miniconda3/lib/python3.3/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/Users/talumbau/miniconda3/lib/python3.3/site-packages/binstar_client/commands/login.py", line 101, in main
    interactive_login(args)
  File "/Users/talumbau/miniconda3/lib/python3.3/site-packages/binstar_client/commands/login.py", line 96, in interactive_login
    token = interactive_get_token(args)
  File "/Users/talumbau/miniconda3/lib/python3.3/site-packages/binstar_client/commands/login.py", line 38, in interactive_get_token
    username = input('Username: ')
AttributeError: 'ColorStream' object has no attribute 'errors'
```

Other anaconda-client commands appear to work:

```
0054-tjalumbaugh:conda.recipe talumbau$ anaconda whoami
Using anaconda-server api site https://api.anaconda.org
Anonymous User
```

```
0054-tjalumbaugh:conda.recipe talumbau$ anaconda logout
Using anaconda-server api site https://api.anaconda.org
You are not logged in
```

Conda version info:
```
0054-tjalumbaugh:conda.recipe talumbau$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.4
  conda-build version : 1.18.1
       python version : 3.3.5.final.0
     requests version : 2.8.1
     root environment : /Users/talumbau/miniconda3  (writable)
  default environment : /Users/talumbau/miniconda3
     envs directories : /Users/talumbau/miniconda3/envs
        package cache : /Users/talumbau/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/trent/osx-64/
                        https://conda.anaconda.org/trent/noarch/
          config file : /Users/talumbau/.condarc
    is foreign system : False
```

The result of `conda update conda` is:

```
0054-tjalumbaugh:conda.recipe talumbau$ conda update conda
Fetching package metadata: ......
# All requested packages already installed.
# packages in environment at /Users/talumbau/miniconda3:
#
conda                     3.18.4                   py33_0
```

The version of `anaconda-client` is:
```
anaconda-client           1.1.2                    py33_0
```

**Comment by talumbau** [comment]
Verified that this does not work on my Mac when `anaconda-client` is installed in a python 3.4 or python 3.5 environment.

**Comment by talumbau** [comment]
The work around is to supply the username and password for logging in at the command line:

```
anaconda login --username <user> --password <pass>
```

**Comment by srossross** [comment]
Thanks for reporting, I will work on a fix.

**Comment by srossross** [comment]
@talumbau can you post the results of `conda list`? I can not reproduce this with a clean python3 environment.

**Comment by talumbau** [comment]
Sure. Running `conda list` in root environment yields:

```
# packages in environment at /Users/talumbau/miniconda3:
#
anaconda-client           1.1.2                    py33_0
backports.ssl-match-hostname 3.4.0.2                   <pip>
binstar                   0.9.1                    py33_0
blz                       0.6.2                np18py33_0
clyent                    1.0.0                    py33_0
conda                     3.18.4                   py33_0
conda-build               1.18.1                   py33_0
conda-env                 2.4.4                    py33_0
cython                    0.20.1                   py33_0
cytoolz                   0.6.1                     <pip>
datashape                 0.2.1.dev0                <pip>
dateutil                  2.1                      py33_2
decorator                 3.4.0                    py33_0
flake8                    2.1.0                     <pip>
flask                     0.10.1                   py33_1
freetype                  2.5.5                         0
h5py                      2.3.0                np18py33_0
hdf5                      1.8.9                         2
ipython                   2.1.0                    py33_2
itsdangerous              0.23                     py33_0
jdcal                     1.0                      py33_0
jinja2                    2.8                      py33_0
jpeg                      8d                            1
libpng                    1.6.17                        0
libsodium                 0.4.5                         0
libtiff                   4.0.6                         0
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvm                      3.3                           0
llvmpy                    0.12.3                   py33_0
lxml                      3.4.4                    py33_0
markupsafe                0.23                     py33_0
mccabe                    0.2.1                     <pip>
multipledispatch          0.4.0                    py33_0
networkx                  1.9                      py33_0
nose                      1.3.1                    py33_0
numba                     0.12.1               np18py33_0
numexpr                   2.3.1                np18py33_0
numpy                     1.8.1                    py33_0
openpyxl                  2.0.2                    py33_0
openssl                   1.0.1k                        1
pandas                    0.14.0                    <pip>
pep8                      1.5.6                     <pip>
pillow                    3.0.0                    py33_1
pip                       7.1.2                    py33_0
ply                       3.4                      py33_0
py                        1.4.20                   py33_0
py4j                      0.8.1                     <pip>
pycosat                   0.6.1                    py33_0
pycparser                 2.10                     py33_0
pyflakes                  0.8.1                     <pip>
pykit                     0.2.0                np18py33_0
pyparsing                 2.0.1                    py33_0
pytables                  3.1.0                np18py33_0
pytest                    2.5.2                    py33_0
python                    3.3.5                         3
python-dateutil           2.4.2                    py33_0
pytz                      2015.7                   py33_0
pyyaml                    3.11                     py33_1
pyzmq                     14.3.1                   py33_0
readline                  6.2                           2
requests                  2.8.1                    py33_0
setuptools                18.4                     py33_0
six                       1.10.0                   py33_0
sqlalchemy                0.9.4                    py33_0
sqlite                    3.8.4.1                       1
ssl_match_hostname        3.4.0.2                  py33_0
tables                    3.1.0                     <pip>
tk                        8.5.18                        0
toolz                     0.7.0                     <pip>
tornado                   3.2.2                    py33_0
werkzeug                  0.9.4                    py33_0
wheel                     0.26.0                   py33_1
xlrd                      0.9.4                    py33_0
xz                        5.0.5                         0
yaml                      0.1.6                         0
zeromq                    4.0.4                         0
zlib                      1.2.8                         0
```

**Comment by srossross** [comment]
Thanks, I will continue to work on this.

**Comment by srossross** [comment]
Quick update, I have fixed this issue here: Anaconda-Server/clyent#4 and I will put it in the next release.

**Comment by srossross** [comment]
I did not mean to close this issue. I will close it when the code is released.

**Comment by stephenakearns** [comment]
Hi @srossross - this is listed in the "externally blocked" pipeline - what is the blocker?

**Comment by srossross** [comment]
@stephenakearns we are waiting on a release in anaconda conda.

**Comment by srossross** [comment]
cc @ilanschnell @csoja

**Comment by srossross** [comment]
This is released! Thanks everyone.

**Comment by amfarrell** [comment]
Those who still see this issue after running `conda update anaconda-client` on python3.5 can fix it by running `conda update clyent`

**Comment by dgergel** [comment]
thanks @amfarrell, this fix worked.
