### ISSUE TITLE
Bug: "anaconda remove" fails with "AttributeError: 'ColorStream' object has no attribute 'errors'"

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Server/anaconda-client#251]
Logged by @electronwill : 

Removing or deleting files and packages with the web interface works but 'anaconda remove wwarner/testci' fails with "AttributeError"

**Comment by stephenakearns** [comment]
@electronwill - can you repro this issue and then copy in the stack trace from the error - by providing the full traceback, it will make the issue very issue to troubleshoot and hopefully fix.

**Comment by srossross** [comment]
I can not reproduce this error.

**Comment by stephenakearns** [comment]
@electronwill Please reopen if u are able to repro

**Comment by electronwill** [comment]
Sure. This was from https://github.com/Anaconda-Server/anaconda-server/issues/823 , but I went ahead and reproduced it using the wwarner3 test account.

```
(cloud)cloud$ anaconda logout
Using anaconda-server api site https://api.anaconda.org
logout successful
(cloud)cloud$ anaconda whoami
Using anaconda-server api site https://api.anaconda.org
Anonymous User
(cloud)cloud$ anaconda login --username wwarner3
Using anaconda-server api site https://api.anaconda.org
wwarner3's Password:
login successful
(cloud)cloud$ anaconda whoami
Using anaconda-server api site https://api.anaconda.org
Username: wwarner3
Member since: Tue Nov 24 20:27:44 2015
  +user_type: user
(cloud)cloud$ anaconda remove wwarner3/testci
Using anaconda-server api site https://api.anaconda.org
[ERROR]
Traceback (most recent call last):
  File "/Users/wwarner/miniconda3/envs/cloud/bin/anaconda", line 6, in <module>
    sys.exit(main())
  File "/Users/wwarner/miniconda3/envs/cloud/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 82, in main
    description=__doc__, version=version)
  File "/Users/wwarner/miniconda3/envs/cloud/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 64, in binstar_main
    return args.main(args)
  File "/Users/wwarner/miniconda3/envs/cloud/lib/python3.5/site-packages/binstar_client/commands/remove.py", line 37, in main
    if args.force or bool_input(msg, False):
  File "/Users/wwarner/miniconda3/envs/cloud/lib/python3.5/site-packages/binstar_client/utils/__init__.py", line 323, in bool_input
    inpt = input('%s %s: ' % (prompt, default_str))
AttributeError: 'ColorStream' object has no attribute 'errors'
(cloud)cloud$
```

**Comment by electronwill** [comment]
It appears that `anaconda remove` is producing the same error produced by `anaconda login` in this issue: https://github.com/Anaconda-Server/anaconda-client/issues/234

**Comment by srossross** [comment]
this is a duplicate issue.
